#---------------------------------------------------#
## 感谢：https://github.com/Hackl0us/SS-Rule-Snippet
#---------------------------------------------------#

# HTTP 代理端口
#port: 7890

# SOCKS5 代理端口
#socks-port: 7891

# Linux 和 macOS 的 redir 代理端口
#redir-port: 7892

#mixed-port: 7890

#ipv6: true

# 允许局域网的连接
#allow-lan: false

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
#mode: rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / error / warning / info / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
#log-level: warning
# Clash 的 RESTful API
#external-controller: '0.0.0.0:9090'

# geodata-mode: true
# geox-url:
#   geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
#   geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
#   mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
#   # asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"

#sniffer:
#  enable: true
 # sniff:
   # HTTP:
 #     ports: [80, 8080-8880]
#      override-destination: true
 #   TLS:
#      ports: [443, 8443]
    # QUIC:
    #   ports: [443, 8443]
 # skip-domain:
#    - 'Mijia Cloud'
#    - 'dlg.io.mi.com'
#    - '+.apple.com'

#dns:
#  enable: true
#  listen: :1053
#  ipv6: true
#  enhanced-mode: redir-host
#  nameserver:
#- 223.5.5.5
#    - 114.114.114.114
#  fallback:
#    - tls://8.8.4.4
#    - tls://1.1.1.1
#    - https://dns.rubyfish.cn/dns-query
#  fallback-filter:
#    ipcidr:
#      - 61.160.148.90/32

#global-client-fingerprint: chrome
#tcp-concurrent: true


proxies: []
proxy-groups:
